[versions]
# App Versions
versionCode = "104"
versionName = "0.1.1"
coroutines = "1.10.2"
coreKtx = "1.17.0"
swipeRefresh = "1.2.0"
# ðŸ‘‡ Firebase Versions
googleServices = "4.4.4"
firebaseBom = "34.8.0"

# SDK Versions
compileSdk = "36"
buildTools = "36.1.0"
minSdk = "26"
targetSdk = "36"

# Plugins
agp = "9.0.0"
kotlin = "2.3.0"

[libraries]
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swipeRefresh" }

# ðŸ‘‡ Firebase Libraries
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-config = { group = "com.google.firebase", name = "firebase-config" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
# ðŸ‘‡ Google Services Plugin
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }