[versions]
# App Versions
versionCode = "105"
versionName = "1.0-rc4"
coroutines = "1.10.2"
coreKtx = "1.17.0"
swipeRefresh = "1.2.0" # ğŸ‘ˆ Ø£Ø¶Ù Ù‡Ø°Ø§ Ø§Ù„Ø³Ø·Ø±

# SDK Versions
compileSdk = "36"
buildTools = "36.1.0"
minSdk = "26"
targetSdk = "36"

# Plugins
agp = "9.0.0"
kotlin = "2.3.0"

[libraries]
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

# ğŸ‘‡ Ø£Ø¶Ù Ù‡Ø°Ø§ Ø§Ù„Ø³Ø·Ø± Ù„ØªØ¹Ø±ÙŠÙ Ø§Ù„Ù…ÙƒØªØ¨Ø©
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swipeRefresh" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }