[versions]
# App Versions
versionCode = "25"
versionName = "2.5"
coroutines = "1.10.2"
coreKtx = "1.15.0"

# SDK Versions
compileSdk = "36"
buildTools = "36.1.0"
minSdk = "26"
targetSdk = "36"

# Plugins
agp = "9.0.0"
kotlin = "2.3.0"

[libraries]
# Add this line:
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
